{
 "title": "Cadence-Server-Basic",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Overall Service Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(cadence_errors[10s])" },
    {
     "expr": "rate(cadence_errors_critical[10s])"
    }
   ]
  },
  {
   "title": "Overall Service Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_requests{cadence_service=\"cadence_frontend\"}[10s])"
    }
   ]
  },
  {
   "title": "Persistence Errors",
   "type": "graph",
   "description": "TODO: how to add rate()? https://stackoverflow.com/questions/66286901/how-to-apply-rate-to-expression-with-name",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"persistence_errors.*\"}"
    }
   ]
  },
  {
   "title": "Persistence Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(persistence_requests[10s])"
    }
   ]
  },
  {
   "title": "Start/Signal Workflow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_requests{operation=\"StartWorkflowExecution\"}[10s])"
    },
    {
     "expr": "rate(cadence_requests{operation=\"SignalWithStartWorkflowExecution\"}[10s])"
    },
    {
     "expr": "rate(cadence_requests{operation=\"SignalWorkflowExecution\"}[10s])"
    }
   ]
  },
  {
   "title": "Activities Started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_requests{operation=\"RecordActivityTaskStarted\"}[10s])"
    }
   ]
  },
  {
   "title": "Decision Started",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_requests{operation=\"RecordDecisionTaskStarted\"}[10s])"
    }
   ]
  },
  {
   "title": "Activity/Decision Polls per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_requests{operation=\"PollForActivityTask\"}[10s])"
    },
    {
     "expr": "rate(cadence_requests{operation=\"PollForDecisionTask\"}[10s])"
    }
   ]
  },
  {
   "title": "Shard Movements",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(sharditem_created_count[10s])"
    },
    {
     "expr": "rate(sharditem_removed_count[10s])"
    },
    { "expr": "rate(shard_closed_count[10s])" },
    {
     "expr": "rate(membership_changed_count[10s])"
    }
   ]
  },
  {
   "title": "Service Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(restarts[10s])" }
   ]
  },
  {
   "title": "Service Panics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(panics[10s])" }
   ]
  },
  {
   "title": "Transfer/Timer Task Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(task_requests[10s])" }
   ]
  },
  {
   "title": "Transfer/Timer Task Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(task_errors[10s])" }
   ]
  },
  {
   "title": "Transfer/Timer Task Latency P95",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_bucket{operation=~\"TimerActive.*\"}[10s])) by (le))",
     "legendFormat": "TimerTask"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(task_latency_bucket{operation=~\"Transfer.*\"}[10s])) by (le))",
     "legendFormat": "Transfer"
    }
   ]
  }
 ]
}