{
 "title": "Cadence-Client",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Workflow/Actiivty Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflow Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Worker__cadence_workflow_endtoend_latency"
    }
   ]
  },
  {
   "title": "Activity Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Worker__cadence_activity_endtoend_latency"
    },
    {
     "expr": "Worker__cadence_activity_execution_latency"
    },
    {
     "expr": "Worker__cadence_activity_execution_latency"
    },
    {
     "expr": "Worker__cadence_activity_response_latency"
    }
   ]
  },
  {
   "title": "Local Activity Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Worker__cadence_local_activity_execution_latency"
    }
   ]
  },
  {
   "title": "Decision/Activity Task Polling Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Worker__cadence_decision_poll_latency"
    },
    {
     "expr": "Worker__cadence_activity_poll_latency"
    }
   ]
  },
  {
   "title": "Decision Latency(Execution/ScheduleToStart)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Worker__cadence_decision_execution_latency"
    },
    {
     "expr": "Worker__cadence_decision_scheduled_to_start_latency"
    },
    {
     "expr": "Worker__cadence_decision_response_latency"
    }
   ]
  },
  { "title": "Workflow Activity Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Workflow Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_workflow_faled[1m]) "
    },
    { "expr": "rate(workflow_timeout[1m])" }
   ]
  },
  {
   "title": "Workflow Normal Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_workflow_completed[1m]) "
    },
    {
     "expr": "rate(Worker__cadence_workflow_start[1m]) "
    },
    {
     "expr": "rate(Worker__cadence_workflow_canceled[1m]) "
    },
    {
     "expr": "rate(Worker__cadence_workflow_continue_as_new[1m]) "
    },
    {
     "expr": "rate(Worker__cadence_workflow_signal_with_start[1m]) "
    }
   ]
  },
  {
   "title": "Activity Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_activity_task_failed[1m])"
    },
    {
     "expr": "rate(Worker__cadence_activity_task_panic[1m])"
    }
   ]
  },
  {
   "title": "Activity Normal Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_activity_task_completed[1m])"
    },
    {
     "expr": "rate(Worker__cadence_activity_task_canceled[1m])"
    },
    {
     "expr": "rate(Worker__cadence_activity_poll_succeed[1m])"
    }
   ]
  },
  {
   "title": "Local Activity Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_local_activity_timeout[1m])"
    },
    {
     "expr": "rate(Worker__cadence_local_activity_failed[1m])"
    },
    {
     "expr": "rate(Worker__cadence_local_activity_panic[1m])"
    }
   ]
  },
  {
   "title": "Local Activity Normal Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_local_activity_total[1m])"
    },
    {
     "expr": "rate(Worker__cadence_local_activity_canceled[1m])"
    }
   ]
  },
  {
   "title": "Decision Execution Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_decision_task_panic[1m])"
    },
    {
     "expr": "rate(Worker__cadence_decision_response_failed[1m])"
    },
    {
     "expr": "rate(Worker__cadence_decision_timeout[1m])"
    },
    {
     "expr": "rate(Worker__cadence_non_deterministic_error[1m])"
    }
   ]
  },
  {
   "title": "Decision Execution Normal Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_decision_task_completed[1m])"
    }
   ]
  },
  {
   "title": "Decision Polling Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_decision_poll_failed[1m])"
    },
    {
     "expr": "rate(Worker__cadence_decision_poll_transient_failed[1m])"
    }
   ]
  },
  {
   "title": "Decision Polling Normal Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_decision_poll_total[1m])"
    },
    {
     "expr": "rate(Worker__cadence_decision_poll_no_task[1m])"
    },
    {
     "expr": "rate(Worker__cadence_decision_poll_succeed[1m])"
    }
   ]
  },
  {
   "title": "Activity Polling Error Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_activity_poll_failed[1m])"
    },
    {
     "expr": "rate(Worker__cadence_activity_poll_transient_failed[1m])"
    }
   ]
  },
  {
   "title": "Activity Polling Normal Counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(Worker__cadence_activity_poll_total[1m])"
    },
    {
     "expr": "rate(Worker__cadence_activity_poll_no_task[1m])"
    },
    {
     "expr": "rate(Worker__cadence_activity_poll_succeed[1m])"
    }
   ]
  },
  { "title": "Sizing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Avg History Size in Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "history_size_sum/history_size_count * 1000000000"
    }
   ]
  },
  {
   "title": "Max/P95 History Count",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(histogram_quantile(0.95, sum(rate(history_count_bucket{operation=\"ExecutionStats\"}[5m])) by (le)) * 1000000000)",
     "legendFormat": "P95"
    },
    {
     "expr": "ceil(histogram_quantile(1.0, sum(rate(history_count_bucket{operation=\"ExecutionStats\"}[5m])) by (le)) * 1000000000)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Avg History Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil((history_count_sum/history_count_count * 1000000000))"
    }
   ]
  },
  {
   "title": "Max/P95 History Size in Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(history_size_bucket{operation=\"ExecutionStats\"}[5m])) by (le)) * 1000000000",
     "legendFormat": "ExecutionStats-P95"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(history_size_bucket{operation=\"SessionStats\"}[5m])) by (le)) * 1000000000",
     "legendFormat": "SessionStats-P95"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(history_size_bucket{operation=\"ExecutionStats\"}[5m])) by (le)) * 1000000000",
     "legendFormat": "ExecutionStats-Max"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(history_size_bucket{operation=\"SessionStats\"}[5m])) by (le)) * 1000000000",
     "legendFormat": "SessionStats-Max"
    }
   ]
  },
  {
   "title": "Avg EventBlobSize in Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil((event_blob_size_sum/event_blob_size_count * 1000000000))"
    }
   ]
  },
  {
   "title": "Max/P95 EventBlobSize in Bytes",
   "type": "graph",
   "description": "TODO",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ceil(histogram_quantile(0.95, sum(rate(event_blob_size_bucket[5m])) by (le)) * 1000000000)",
     "legendFormat": "P95"
    },
    {
     "expr": "ceil(histogram_quantile(1.0, sum(rate(event_blob_size_bucket[5m])) by (le)) * 1000000000)",
     "legendFormat": "Max"
    }
   ]
  }
 ]
}