server:
  frontend:
    replicaCount: 1
  history:
    replicaCount: 1
  matching:
    replicaCount: 1
  worker:
    replicaCount: 1

  config:

    # IMPORTANT: This value cannot be changed, once it's set.
    numHistoryShards: 512
    
    persistence:
      default:
        driver: "sql"

        sql:
          pluginName: "mysql"
          host: "<FILL IT HERE>.rds.amazonaws.com"
          port: 3306
          database: cadence
          user: "<FILL IT HERE>"
          password: "<FILL IT HERE>"
          connectAttributes:
            tx_isolation: "READ-COMMITTED"

      visibility:
        driver: "sql"

        sql:
          pluginName: "mysql"
          host: "<FILL IT HERE>.rds.amazonaws.com"
          port: 3306
          database: cadence_visibility
          user: "<FILL IT HERE>"
          password: "<FILL IT HERE>"
          connectAttributes:
            tx_isolation: "READ-COMMITTED"

cassandra:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
